### ISSUE TITLE
Selection of text in Label tool on Firefox not working

### ISSUE THREAD

**Issue by erikbuunk** [SbstnErhrdt/labeling#3]
The selection of text does not work on Firefox. It works on Safari on the same laptop.

## Steps
- OpenHome>Organizations>MPI-INNO>Logic-Mill>Label Abstracts   and then Start Labeling
- Select text to remove with the mouse

## Result
- Nothing happens
- Error in the console:
```
TypeError: t.baseNode is undefined
    NuxtJS 4
        selectText
        ee
        n
        _wrapper
```
## Expected behavior
- text turns red and is add to list of text to remove

## System info:

- OS: MacOS 11.6
- Firefox: 95.0.2 (64-bit)

**Comment by SbstnErhrdt** [comment]
Chrome and Firefox have different attribute names:

https://developer.mozilla.org/en-US/docs/Web/API/Selection/anchorNode

```
According to MDN

selection.anchorNode - returns the Node in which the selection begins.

selection.focusNode - returns the Node in which the selection ends.

because there were debates on naming:

baseNode is alias for anchorNode
extentNode for focusNode
Note: references to both baseNode and extentNode have been removed from the MDN page.

```

https://stackoverflow.com/questions/27241281/what-is-anchornode-basenode-extentnode-and-focusnode-in-the-object-returned

Thanks for reporting @erikbuunk
