### ISSUE TITLE
Reselecting text gives unexpected results

### ISSUE THREAD

**Issue by erikbuunk** [SbstnErhrdt/labeling#5]
When including an existing selection in a new selection, a very large arbitrary area is being selected.

![image](https://user-images.githubusercontent.com/55157851/149145407-b9e23513-673a-4c4f-bb6a-952d11cd613c.png)

Now select `specimens. Results: the mean`

Result:
![image](https://user-images.githubusercontent.com/55157851/149145540-8ed8dd4d-5335-4cdc-b45c-57db898be249.png)

After that, no normal selection can be made

Work around:
- Reset all

**Comment by SbstnErhrdt** [comment]
Thanks for bringing this up.

I have implemented now a case for that
```javascript
      // prevent the selection of overlapping nodes
      if (selection.anchorNode !== selection.focusNode) {
        console.warn('can not select text of different nodes')
        return;
      }
 ```     
 
 Should be working now. 
 @erikbuunk pls confirm.

**Comment by erikbuunk** [comment]
@SbstnErhrdt Yes it works, thanks! I can think of some UI/UX improvements but that is not for the MVP. The main thing is that the weird behavior is solved. I will close this issue.
